var countries = [
    {"co":"au","ph":"61","uk":"Австралія","en":"Australia"},
    {"co":"at","ph":"43","uk":"Австрія","en":"Austria"},
    {"co":"bd","ph":"880","uk":"Бангладеш","en":"Bangladesh"},
    {"co":"by","ph":"375","uk":"Білорусь","en":"Belarus"},
    {"co":"be","ph":"32","uk":"Бельгія","en":"Belgium"},
    {"co":"br","ph":"55","uk":"Бразилія","en":"Brazil"},
    {"co":"bg","ph":"359","uk":"Болгарія","en":"Bulgaria"},
    {"co":"ca","ph":"1","uk":"Канада","en":"Canada"},
    {"co":"cl","ph":"56","uk":"Чилі","en":"Chile"},
    {"co":"cn","ph":"86","uk":"Китай","en":"China"},
    {"co":"cz","ph":"420","uk":"Чехія","en":"Czech Republic"},
    {"co":"dk","ph":"45","uk":"Данія","en":"Denmark"},
    {"co":"do","ph":"1","uk":"Домініканська Республіка","en":"Dominican Republic"},
    {"co":"ec","ph":"593","uk":"Еквадор","en":"Ecuador"},
    {"co":"ee","ph":"372","uk":"Естонія","en":"Estonia"},
    {"co":"fi","ph":"358","uk":"Фінляндія","en":"Finland"},
    {"co":"fr","ph":"33","uk":"Франція","en":"France"},
    {"co":"de","ph":"49","uk":"Німеччина","en":"Germany"},
    {"co":"gr","ph":"30","uk":"Греція","en":"Greece"},
    {"co":"gt","ph":"502","uk":"Гватемала","en":"Guatemala"},
    {"co":"hk","ph":"852","uk":"Гонконг","en":"Hong Kong"},
    {"co":"hu","ph":"36","uk":"Угорщина","en":"Hungary"},
    {"co":"in","ph":"91","uk":"Індія","en":"India"},
    {"co":"id","ph":"62","uk":"Індонезія","en":"Indonesia"},
    {"co":"ir","ph":"98","uk":"Іран","en":"Iran"},
    {"co":"iq","ph":"964","uk":"Ірак","en":"Iraq"},
    {"co":"is","ph":"354","uk":"Ісландія","en":"Iceland"},
    {"co":"il","ph":"972","uk":"Ізраїль","en":"Israel"},
    {"co":"it","ph":"39","uk":"Італія","en":"Italy"},
    {"co":"jp","ph":"81","uk":"Японія","en":"Japan"},
    {"co":"kz","ph":"7","uk":"Казахстан","en":"Kazakhstan"},
    {"co":"kr","ph":"82","uk":"Південна Корея","en":"South Korea"},
    {"co":"kw","ph":"965","uk":"Кувейт","en":"Kuwait"},
    {"co":"kg","ph":"996","uk":"Киргизстан","en":"Kyrgyzstan"},
    {"co":"la","ph":"856","uk":"Лаос","en":"Laos"},
    {"co":"lv","ph":"371","uk":"Латвія","en":"Latvia"},
    {"co":"lb","ph":"961","uk":"Ліван","en":"Lebanon"},
    {"co":"lt","ph":"370","uk":"Литва","en":"Lithuania"},
    {"co":"lu","ph":"352","uk":"Люксембург","en":"Luxembourg"},
    {"co":"my","ph":"60","uk":"Малайзія","en":"Malaysia"},
    {"co":"mk","ph":"389","uk":"Македонія","en":"North Macedonia"},
    {"co":"mt","ph":"356","uk":"Мальта","en":"Malta"},
    {"co":"mx","ph":"52","uk":"Мексика","en":"Mexico"},
    {"co":"md","ph":"373","uk":"Молдова","en":"Moldova"},
    {"co":"mn","ph":"976","uk":"Монголія","en":"Mongolia"},
    {"co":"me","ph":"382","uk":"Чорногорія","en":"Montenegro"},
    {"co":"ma","ph":"212","uk":"Марокко","en":"Morocco"},
    {"co":"np","ph":"977","uk":"Непал","en":"Nepal"},
    {"co":"nl","ph":"31","uk":"Нідерланди","en":"Netherlands"},
    {"co":"nz","ph":"64","uk":"Нова Зеландія","en":"New Zealand"},
    {"co":"no","ph":"47","uk":"Норвегія","en":"Norway"},
    {"co":"pk","ph":"92","uk":"Пакистан","en":"Pakistan"},
    {"co":"pe","ph":"51","uk":"Перу","en":"Peru"},
    {"co":"ph","ph":"63","uk":"Філіппіни","en":"Philippines"},
    {"co":"pl","ph":"48","uk":"Польща","en":"Poland"},
    {"co":"pt","ph":"351","uk":"Португалія","en":"Portugal"},
    {"co":"pr","ph":"1","uk":"Пуерто-Рико","en":"Puerto Rico"},
    {"co":"qa","ph":"974","uk":"Катар","en":"Qatar"},
    {"co":"ro","ph":"40","uk":"Румунія","en":"Romania"},
    {"co":"ru","ph":"7","uk":"Росія","en":"Russia"},
    {"co":"sa","ph":"966","uk":"Саудівська Аравія","en":"Saudi Arabia"},
    {"co":"rs","ph":"381","uk":"Сербія","en":"Serbia"},
    {"co":"sg","ph":"65","uk":"Сінгапур","en":"Singapore"},
    {"co":"sk","ph":"421","uk":"Словаччина","en":"Slovakia"},
    {"co":"si","ph":"386","uk":"Словенія","en":"Slovenia"},
    {"co":"za","ph":"27","uk":"Південна Африка","en":"South Africa"},
    {"co":"es","ph":"34","uk":"Іспанія","en":"Spain"},
    {"co":"lk","ph":"94","uk":"Шрі-Ланка","en":"Sri Lanka"},
    {"co":"se","ph":"46","uk":"Швеція","en":"Sweden"},
    {"co":"ch","ph":"41","uk":"Швейцарія","en":"Switzerland"},
    {"co":"sy","ph":"963","uk":"Сирія","en":"Syria"},
    {"co":"tj","ph":"992","uk":"Таджикистан","en":"Tajikistan"},
    {"co":"th","ph":"66","uk":"Таїланд","en":"Thailand"},
    {"co":"tr","ph":"90","uk":"Туреччина","en":"Turkey"},
    {"co":"ua","ph":"380","uk":"Україна","en":"Ukraine"},
    {"co":"ae","ph":"971","uk":"ОАЕ","en":"United Arab Emirates"},
    {"co":"gb","ph":"44","uk":"Велика Британія","en":"United Kingdom"},
    {"co":"us","ph":"1","uk":"США","en":"United States"},
    {"co":"uy","ph":"598","uk":"Уругвай","en":"Uruguay"},
    {"co":"uz","ph":"998","uk":"Узбекистан","en":"Uzbekistan"},
    {"co":"ve","ph":"58","uk":"Венесуела","en":"Venezuela"},
    {"co":"vn","ph":"84","uk":"В'єтнам","en":"Vietnam"},
    {"co":"ye","ph":"967","uk":"Ємен","en":"Yemen"},
    {"co":"zm","ph":"260","uk":"Замбія","en":"Zambia"},
    {"co":"zw","ph":"263","uk":"Зімбабве","en":"Zimbabwe"}
];
